name: Release
on:
  workflow_dispatch:
    inputs:
      branch:
        description: "Branch"
        required: true
        default: "main"
      tag:
        description: "Release Tag"
        required: true
permissions:
  id-token: write
  contents: write

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    env:
      GITHUB_WORKFLOW_URL: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
      TAG: ${{ github.event.inputs.tag }}
      BRANCH: ${{ github.event.inputs.branch }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: "Release tag '${{ github.event.inputs.tag }}' should be semver prefixed with 'v'"
        shell: bash
        run: |
          if [[ ! $TAG =~ ^v[0-9]+\.[0-9]+\.[0-9]+(-[0-9A-Za-z.-]+)?$ ]]; then
            echo "::error::Invalid tag '${TAG}'. Tags must start with 'v' and follow semver (vMAJOR.MINOR.PATCH[-PRERELEASE])."
            exit 1
          fi

      - name: Hub login
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERBUILDBOT_USERNAME }}
          password: ${{ secrets.DOCKERBUILDBOT_WRITE_PAT }}

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver: cloud
          endpoint: "docker/secrets-engine"
          install: true

      - name: Build NRI Plugin
        run: make BUILDER=${{ steps.buildx.outputs.name }} nri-plugin-package

      - name: Ship it
        uses: ncipollo/release-action@v1
        with:
          artifacts: "./dist/*.tar.gz"
          draft: true
          tag: ${{ env.TAG }}
          commit: ${{ env.BRANCH }}
          generateReleaseNotes: true

      - name: Create module tags
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git tag client/${TAG}
          git tag engine/${TAG}
          git tag plugin/${TAG}
          git tag store/${TAG}

      - name: Push tags
        run: git push origin --tags
