name: Release
on:
  workflow_dispatch:
    inputs:
      branch:
        description: "Branch"
        required: true
        default: "main"
      tag:
        description: "Release Tag"
permissions:
  contents: write

jobs:
  release:
    name: Release NRI Plugin
    runs-on: ubuntu-latest
    env:
      GITHUB_WORKFLOW_URL: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
    steps:
      - name: Generate app token
        uses: tibdex/github-app-token@v1
        id: generate_token
        with:
          app_id: ${{ vars.DESKTOP_GITHUB_CONTENT_APP_ID }}
          private_key: ${{ secrets.DESKTOP_GITHUB_CONTENT_APP_SECRET }}

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Hub login
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERBUILDBOT_USERNAME }}
          password: ${{ secrets.DOCKERBUILDBOT_WRITE_PAT }}

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver: cloud
          endpoint: "docker/secrets-engine"
          install: true

      - name: Build NRI Plugin
        run: make BUILDER=${{ steps.buildx.outputs.name }} nri-plugin-package

      - name: Ship it
        if: ${{ github.event.inputs.tag != '' }} # don't release if no tag is specified
        uses: ncipollo/release-action@v1
        with:
          artifacts: "./dist/*.tar.gz"
          prerelease: true
          draft: false
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.event.inputs.tag }}
          commit: ${{ github.event.inputs.branch }}